app/ask_me/urls.py
from django.conf.urls import url
from ask_me.views import *
from django.contrib.auth.decorators import login_required

from .models import LikeDislike
from ask_me.models import Question, Answer

# app_name = 'ask_me'
urlpatterns = [
    url(r'^$', main),

    url(r'^feed/$', feed, name='feed'),
    url(r'^hot/$', hot, name='hot'),
    url(r'^tag/(?P<tag>.*)/$', tag, name='tag'),
    url(r'^question/(?P<question_id>[0-9]+)/$', question, name='question'),
    url(r'^question/(?P<question_id>[0-9]+)/answer/$', new_answer, name='new_answer'),
    url(r'^users/$', users, name='users'),

    url(r'^signin/$', signin, name='signin'),
    url(r'^signout/$', signout, name='signout'),
    url(r'^signup/$', signup, name='signup'),

    url(r'^ask/$', new_question, name='new_question'),
    url(r'^settings/$', settings, name='settings'),

    url(r'^question/delete/$', delete_question, name='delete_question'),
    url(r'^answer/delete/$', delete_answer, name='delete_answer'),
    url(r'^user/delete/$', delete_user, name='delete_user'),

    url(r'^search/$', search, name='search'),
    url(r'^user/(?P<username>[a-zA-Zа-яА-Я_\-\.0-9]+?)$', profile, name='profile'),

    url(r'^api/question/(?P<pk>\d+)/like/$', login_required(VotesView.as_view(model=Question, vote_type=LikeDislike.LIKE)), name='question_like'),
    url(r'^api/question/(?P<pk>\d+)/dislike/$', login_required(VotesView.as_view(model=Question, vote_type=LikeDislike.DISLIKE)), name='question_dislike'),
    url(r'^api/answer/(?P<pk>\d+)/like/$', login_required(VotesView.as_view(model=Answer, vote_type=LikeDislike.LIKE)), name='answer_like'),
    url(r'^api/answer/(?P<pk>\d+)/dislike/$', login_required(VotesView.as_view(model=Answer, vote_type=LikeDislike.DISLIKE)), name='answer_dislike'),
]

app/question_ask_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ask_me.urls'), name='ask_me')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/ask_me/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
import os
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image, ExifTags

from ask_me.managers import UserManager, TagManager, QuestionManager, AnswerManager, LikeDislikeManager


# AUTH_USER_MODEL set in settings
class User(AbstractUser):
    upload = models.ImageField(default="default/default_avatar.png", upload_to="uploads/%Y/%m/%d/", verbose_name="User's Avatar")
    registration_date = models.DateTimeField(default=timezone.now, verbose_name="User's Registration Date")
    rating = models.IntegerField(default=0, verbose_name="User's Rating")

    objects = UserManager()

    def __str__(self):
        return self.username

# functions for correct uploading avatar
def rotate_image(filepath):
    try:
        image = Image.open(filepath)
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        exif = dict(image._getexif().items())

        if exif[orientation] == 3:
            image = image.rotate(180, expand=True)
        elif exif[orientation] == 6:
            image = image.rotate(270, expand=True)
        elif exif[orientation] == 8:
            image = image.rotate(90, expand=True)
        image.save(filepath)
        image.close()
    except (AttributeError, KeyError, IndexError):
        pass

@receiver(post_save, sender=User, dispatch_uid="update_image_profile")
def update_image(sender, instance, **kwargs):
    if instance.upload:
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        fullpath = BASE_DIR + instance.upload.url
        rotate_image(fullpath)



class Tag(models.Model):
    name = models.CharField(max_length=20, default="404", verbose_name="Question's Tag")

    objects = TagManager()

    def __str__(self):
        return self.name


class LikeDislike(models.Model):
    LIKE = 1
    DISLIKE = -1

    VOTES = (
        (DISLIKE, 'Dislike'),
        (LIKE, 'Like')
    )

    vote = models.SmallIntegerField(verbose_name=("Vote"), choices=VOTES)
    user = models.ForeignKey(User, verbose_name=("User"))

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = LikeDislikeManager()

    def __str__(self):
        return self.user.username + " liked"


class Question(models.Model):
    author = models.ForeignKey(User, verbose_name="Question's Owner")
    title = models.CharField(max_length=50, verbose_name="Question's Header")
    text = models.TextField(verbose_name="Question's Content")
    date = models.DateTimeField(default=timezone.now, verbose_name="Question's Date")
    rating = models.IntegerField(default=0, null=False, verbose_name="Question's Rating")
    is_active = models.BooleanField(default=True, verbose_name="Question's Availability")
    tags = models.ManyToManyField(Tag, default=True, related_name='questions', verbose_name="Question's Tags")
    votes = GenericRelation(LikeDislike, related_query_name='questions')

    objects = QuestionManager()

    def __str__(self):
        return self.text


class Answer(models.Model):
    author = models.ForeignKey(User, verbose_name="Answer's Owner")
    date = models.DateTimeField(default=timezone.now, verbose_name="Answer's Date")
    question = models.ForeignKey(Question, related_name='answers', verbose_name="Answer's Question")
    text = models.TextField(verbose_name="Answer's Content")
    rating = models.IntegerField(default=0, null=False, verbose_name="Answer's Rating")
    votes = GenericRelation(LikeDislike, related_query_name='answers')

    objects = AnswerManager()

    def __str__(self):
        return self.text

app/ask_me/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404, HttpResponseForbidden as Http403, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
import json

from ask_me.models import *
from ask_me.forms import UserRegistrationForm, UserLoginForm, NewQuestionForm, UserSettingsForm, AnswerForm


def main(request):
	return redirect('feed')


def feed(request):
	return render(request, 'feed.html',
                  {'questions': paginator(request, objects_list=Question.objects.get_new()),
				   'headers': header_content("new")
				   })


def hot(request):
	return render(request, 'feed.html',
				  {'questions': paginator(request, objects_list=Question.objects.get_hot()),
				   'headers': header_content("hot")
				   })


def tag(request, tag):
	return render(request, 'feed.html',
				  {'questions': paginator(request, objects_list=Tag.objects.get_by_tag(tag_name=tag)),
				   'headers': header_content("tag", tag_name=tag)
				   })


def question(request, question_id):
	question = Question.objects.get_by_id(int(question_id)).first()
	if question is not None:
		answers = paginator(request, objects_list=Answer.objects.get_hot_for_answer(question.id))
		return render(request, 'question.html', {'question': question, 'answers': answers})
	else:
		raise Http404


def users(request):
	users = paginator(request, objects_list=User.objects.by_first_name())
	return render(request, 'users.html', {'users': users})


def signup(request):
	if request.method == 'POST':
		form = UserRegistrationForm(request.POST, request.FILES)
		if form.is_valid():
			user = form.save()
			user.set_password(form.cleaned_data['password'])
			user.save()
			login(request, user)
			return redirect('/')
	else:
		form = UserRegistrationForm()
		logout(request)
	return render(request, 'signup.html', {'form': form})


def signin(request):
	if request.method == 'POST':
		form = UserLoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect(request.GET.get('next') if request.GET.get('next') != '' else '/')
	else:
		form = UserLoginForm()
		logout(request)
	return render(request, 'signin.html', {'form': form})


def signout(request):
	if not request.user.is_authenticated:
		raise Http404
	logout(request)
	return redirect(request.GET['from'])


@login_required(login_url='/signin/')
def new_question(request):
	if request.method == 'POST':
		form = NewQuestionForm(request.POST)
		if form.is_valid():
			ques = Question.objects.create(author=request.user,
							date=timezone.now(),
							is_active=True,
							title=form.cleaned_data['title'],
							text=form.cleaned_data['text'])
			ques.save()

			for tagTitle in form.cleaned_data['tags'].split():
				tag = Tag.objects.get_or_create(name=tagTitle)[0]
				ques.tags.add(tag)
				ques.save()
			return question(request, ques.id)
	else:
		form = NewQuestionForm()
	return render(request, 'new_question.html', {'form': form})


@login_required(login_url='/signin/')
def new_answer(request, question_id):
	if Question.objects.filter(id=question_id).exists():
		if request.method == 'POST':
			form = AnswerForm(request.POST)
			if form.is_valid():
				answeredQuestion = Question.objects.get_by_id(question_id)[0]
				answer = Answer.objects.create(author=request.user,
								date=timezone.now(),
								text=form.cleaned_data['text'],
								question_id=answeredQuestion.id)
				answer.save()
				return redirect('/question/{}/#{}'.format(question_id, answer.id))
		else:
			form = AnswerForm()
		return render(request, 'answer.html', {'form': form})
	else:
		raise Http404


def profile(request, username):
	user = User.objects.by_username(username)
	if user is not None:
		return render(request, 'profile.html', {'profile': user})
	else:
		raise Http404


@login_required(login_url='/signin/')
def settings(request):
	user = get_object_or_404(User, username=request.user)

	if request.method == 'POST':
		form = UserSettingsForm(instance=user,
                               data=request.POST,
                               files=request.FILES
                              )
		if form.is_valid():
			form.save()
			return profile(request, user.username)
	else:
		form = UserSettingsForm(instance=user)

	return render(request, 'settings.html', {'form': form})


@login_required(login_url='/signin/')
def delete_user(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		user = User.objects.by_username(username)
		user.delete()
		return redirect('/')
	else:
		return render(request, 'delete_profile_confirmation.html')


@login_required(login_url='/signin/')
def delete_question(request):
	if request.method == 'POST':
		question_id = int(request.POST.get('question_id'))
		question = Question.objects.get(id=question_id)
		if question.author.id != request.user.id:
			raise Http403
		question.delete()
		return redirect('/')
	else:
		raise Http404


@login_required(login_url='/signin/')
def delete_answer(request):
	if request.method == 'POST':
		answer_id = int(request.POST.get('answer_id'))
		answer = Answer.objects.get(id=answer_id)
		if answer.author.id != request.user.id:
			raise Http403
		answer.delete()
		return redirect('/')
	else:
		raise Http404


def search(request):
	if request.method == 'GET' and 'tag' in request.GET:
		tag_search = request.GET.get('tag')
		try:
			return tag(request, tag_search)
		except AttributeError:
			return redirect('/')
	else:
		raise Http404


class VotesView(View):
	model = None  # Data Model - Articles or Comments
	vote_type = None  # Vote type Like/Dislike

	def post(self, request, pk):
		obj = self.model.objects.get(pk=pk)
		# GenericForeignKey does not support get_or_create
		try:
			likedislike = LikeDislike.objects.get(content_type=ContentType.objects.get_for_model(obj), object_id=obj.id,
												  user=request.user)
			if likedislike.vote is not self.vote_type:
				likedislike.vote = self.vote_type
				likedislike.save(update_fields=['vote'])
				result = True
			else:
				likedislike.delete()
				result = False
		except LikeDislike.DoesNotExist:
			obj.votes.create(user=request.user, vote=self.vote_type)
			result = True

		return HttpResponse(
			json.dumps({
				"result": result,
				"like_count": obj.votes.likes().count(),
				"dislike_count": obj.votes.dislikes().count(),
				"sum_rating": obj.votes.sum_rating()
			}),
			content_type="application/json"
		)


def paginator(request, objects_list):
	paginator = Paginator(objects_list, 20)  # Show 20 contacts per page

	page = request.GET.get('page')

	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		objects = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		objects = paginator.page(paginator.num_pages)

	return objects


def header_content(type, tag_name=""):
    if (type == "new"):
        content_header = [
            {'title': 'New Questions', 'url': 'feed', 'is_active': True},
            {'title': 'Hot Questions', 'url': 'hot', 'is_active': False}
        ]
    if (type == "hot"):
        content_header = [
            {'title': 'New Questions', 'url': 'feed', 'is_active': False},
            {'title': 'Hot Questions', 'url': 'hot', 'is_active': True}
        ]
    if (type == "tag"):
        content_header = [
            {'title': 'Tag: ' + tag_name, 'url': 'feed', 'is_active': True},
        ]
    return content_header

app/ask_me/templates/answer.html
{% extends 'base.html' %}

{% load static %}

{% block headerName %}
    <h3>Write the answer</h3>
{% endblock %}

{% block content %}
        <form class="form-horizontal" action="{{ request.path }}" method="post">
            {% csrf_token %}

            <div class="col-md-12">
                <div class="form-group">{{ form.text }}</div>
            </div>

            <input type="submit" value="Answer" class="btn btn-success"/>
        </form>
{% endblock %}

app/ask_me/templates/base.html
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'src/icon.png' %}" type="image/png">
    <title>Ask me</title>
    {% block styles %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size: 30px; font-family: 'Ubuntu Mono'; font-weight: bold" href="/">AskMe</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <ul class="navbar-form navbar-left">
                        <form action="{% url 'search' %}" type="get" style="margin: 0; margin-left: 15px">
                            <div class="search-line">
                                <input type="text" class="form-control search-query" name="tag" placeholder="Search for tag...">
                            </div>
                            <div class="search-btn">
                                <button type="submit" class="btn btn-danger">Search</button>
                            </div>
                        </form>
                    </ul>
                    <ul class="navbar-form navbar-left">
                        <a href="{% url 'new_question' %}"><button type="button" class="btn btn-success">ASK!</button></a>
                    </ul>
                </ul>

                {% if user.is_authenticated %}
                    <ul class="navbar-form navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <img class="avatar-on-nav" src="/media/{{ user.upload }}">
                                <span class="name-nav">
                                    {{ user.first_name }} {{ user.last_name }} [{{ user.username }}]
                                </span>
                                <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li><a href="{% url 'profile' user.username %}"><span class="glyphicon glyphicon-user"></span> My Profile</a></li>
                                <li><a href="{% url 'settings' %}"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
                                <li><a href="/signout/?from={{ request.get_full_path }}"><span class="glyphicon glyphicon-log-out"></span> Sign out</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'signin' %}"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
                        <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-new-window"></span> Sign Up</a></li>
                    </ul>
                {% endif %}

                <ul class="navbar-form">
                    <a href="{% url 'users' %}">
                        <span class="glyphicon glyphicon-user" style="font-size: 30px; color: white">
                        </span>
                    </a>
                </ul>

            </div>
        </div>
    </nav>


    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="col-md-12">
                    {% block headerName %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="col-12 col-md-10">
            {% block messages %}
                <div class="main">
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% if form.username.errors %}
                        {% for error in form.username.errors %}
                            <div class="alert alert-danger" role="alert">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% if form.password.errors %}
                        {% for error in form.password.errors %}
                            <div class="alert alert-danger" role="alert">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>

        <div class="col-6 col-md-2 ">
            <div class="well well-sm">
                <div class="popular">
                    <h4>Popular</h4>
                </div> <hr>
                    {% for top_tag in top_tags %}
                        <a class="tag{{ forloop.counter }}" href="{% url 'tag' top_tag.name %}">{{ top_tag.name }}</a>
                    {% endfor %}
            </div>

            <div class="well well-sm">
                <div class="popular">
                    <h4>Top People</h4>
                </div> <hr>

                {% for top_user in top_users %}
                  <li class="list-group-item" style="text-align: center;">
                    <a class="peo" href="{% url 'profile' top_user.username %}">{{ top_user.first_name }} {{ top_user.last_name }} <span class="glyphicon glyphicon-star"></span></a>
                  </li>
                {% endfor %}
            </div>
        </div>
    </div>

    {% block footer %}
    {% endblock %}

    <script src="{% static 'jquery/jquery-latest.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

    {% block custom_javascript %}{% endblock %}
</body>
</html>

app/ask_me/templates/delete_profile_confirmation.html
{% extends "base.html" %}
{% load static %}

{% block headerName %}
    <h1>Account Deleting</h1>
{% endblock %}

{% block content %}
    <div>
        <h3>Are you sure you want to delete your account?</h3>
        <form enctype="multipart/form-data" class="form-horizontal" action="{% url 'delete_user' %}" method="post">
            {% csrf_token %}
            <div class="col-md-6">
                <fieldset>
                    <input type="hidden" name="username" value="{{ user.username }}">
                    <div class="form-group">
                        <input type="submit" value="Yes, I am sure!" class="btn btn-success"/>
                    </div>
                </fieldset>
            </div>
        </form>
    </div>
{% endblock %}

app/ask_me/templates/feed.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/questions.css' %}">
{% endblock %}

{% block headerName %}
        <h3>
            <ul class="nav nav-pills">
                {% for header in headers %}
                    {% if header.is_active %}
                        <li class="active"><a href="{% url header.url %}" >{{ header.title }}</a></li>
                    {% else %}
                        <li><a href="{% url header.url %}" >{{ header.title }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </h3>
{% endblock %}

{% block content %}

    {% for question in questions %}
        <div class="masthead-lead">
            <div class="media">

                <div class="media-left">
                    <a href="{% url 'profile' question.author.username %}">
                        <img src="/media/{{ question.author.upload }}" class="avatar-on-post">
                    </a> <br><br>
                </div>

                <div class="media-body">
                    <a href="{% url 'question' question.id %}"><h4 class="media-heading">{{ question.title }}</h4></a>
                    <small >
                        <i style="font-size: small; font-weight: bold">{{ question.author.first_name }} {{ question.author.last_name }}</i>
                        <i style="font-size: small">Posted {{ question.date }}</i>
                    </small>
                    <br><br>

                    <p class="content">{{ question.text | truncatechars:300 }}</p>
                    <br>

                    {% for tag in question.tags.all %}
                        <a href="{% url 'tag' tag.name %}" style="text-decoration: none">
                            <button type="button" class="btn btn-primary btn-xs">{{ tag.name }}</button>
                        </a>
                    {% endfor %}

                    {% if user.is_authenticated %}
                        <div class="likes">
                            <button type="button" class="btn btn-success btn-sm" data-id="{{ question.id }}" data-type="question" data-action="like" title="Like">
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <span data-count="like">{{ question.votes.likes.count }}</span>
                            </button>

                            <button type="button" class="btn btn-danger btn-sm dislike-color" data-id="{{ question.id }}" data-type="question" data-action="dislike" title="Dislike">
                                <span class="glyphicon glyphicon-thumbs-down"></span>
                                <span data-count="dislike">{{ question.votes.dislikes.count }}</span>
                            </button>
                        </div>
                    {% endif %}
              </div>

            </div>
            <br>
            <hr class="masthead-hr">
        </div>
    {% endfor %}

{% endblock %}

{% block footer %}
    {% if questions.has_next %}
        <div class="container">
            <ul class="pagination">
                {% if questions.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.previous_page_number }}">Back</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.previous_page_number }}">{{ questions.previous_page_number }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Back</a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="#">{{ questions.number }} <span class="sr-only">(current)</span></a>
                </li>

                {% if questions.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.next_page_number }}">{{ questions.next_page_number }}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ questions.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    <script src="{% static 'js/like.js' %}"></script>
{% endblock %}

app/ask_me/templates/new_question.html
{% extends "base.html" %}
{% load static %}

{% block headerName %}
    <h2>New Question</h2>
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'new_question' %}" method="post">
        {% csrf_token %}

        <div class="col-md-12">
            <fieldset>

                {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                    </div>
                {% endfor %}

                <div class="form-group">
                    <input type="submit" value="ASK!" class="btn btn-success"/>
                </div>
            </fieldset>
        </div>

    </form>
{% endblock %}

app/ask_me/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block headerName %}
    <h1>{{ profile.username }}</h1>
{% endblock %}

{% block content %}
    <div class="masthead-lead">
        <div class="avatar-block">
            <img class="avatar" src="/media/{{ profile.upload }}">
        </div>
        <div class="profile-info-block">
            <h4><i>First name: </i> {{ profile.first_name }}</h4>
            <h4><i>Last name: </i>{{ profile.last_name }}</h4>
            <h4><i>Email: </i>{{ profile.email }}</h4>
            <hr>
            <h4>
                <i>Questions: </i>{{ profile.question_set.all | length }}
                <i>Answers: </i>{{ profile.answer_set.all | length }}
            </h4>
        </div>
        <hr>

        <div class="activity">
            <table>
                <tr>
                    <th><h3>Questions</h3></th>
                    <th><h3>Answers</h3></th>
                </tr>
                <td class="questions">
                    {% for q in profile.question_set.get_hot %}
                        <div class="list-group">
                            <a href="{% url 'question' q.id %}" class="list-group-item">
                                <div class="rate">
                                    <img class="rate-icon" src="/media/default/stats.png" alt="">
                                    {{ q.rating }}
                                </div>
                                <div class="header">
                                    <h4 class="list-group-item-heading">{{ q.title }}</h4>
                                    <h5>{{ q.date }}</h5>
                                </div>
                                {% for tag in q.tags.all %}
                                    <span class="label label-danger">{{ tag.title }}</span>
                                {% endfor %}
                            </a>
                        </div>
                    {% endfor %}
                </td>
                <td>
                    {% for a in profile.answer_set.get_all_hot %}
                        <div class="questions list-group">
                            <a href="/question/{{ a.question_id }}/#{{ a.id }}" class="list-group-item">
                                <div class="rate">
                                    <img class="rate-icon" src="/media/default/stats.png" alt="">
                                    {{ a.rating }}
                                </div>
                                <h4>{{ a.question.title }}</h4>
                                <hr>
                                <p>{{ a.text }}</p>
                            </a>
                        </div>
                    {% endfor %}
                </td>
            </table>
        </div>

    </div>
{% endblock %}

app/ask_me/templates/settings.html
{% extends "base.html" %}
{% load static %}

{% block headerName %}
    <h1>Settings: W. Smith</h1>
    {% if user.is_authenticated %}
        <span><a href="{% url 'delete_user' %}">Delete an account</a></span>
    {% endif %}
{% endblock %}

{% block content %}
    <div>
        <form enctype="multipart/form-data" class="form-horizontal" action="{% url 'settings' %}" method="post">
            {% csrf_token %}
            <div class="col-md-6">
                <fieldset>

                    {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                    </div>
                    {% endfor %}

                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success"/>
                    </div>
                </fieldset>
            </div>
        </form>
    </div>
{% endblock %}